using System;
using System.Collections.Generic;
using UnityEngine;
using UMT;

namespace MMDPlayer
{
    /// <summary>
    /// Structured index of every imported PMX model and its ready-to-play motion clips.
    /// Populated at edit time by <see cref="MMDPlayer.Editor.MMDResourcesScanner"/> and read at runtime.
    /// </summary>
    [CreateAssetMenu(fileName = "MMDAssetLibrary", menuName = "MMD Player/Asset Library")]
    public sealed class MMDAssetLibrary : ScriptableObject
    {
        /// <summary>
        /// One model and the motion clips that have been converted (from the model's VMDs)
        /// into playable Unity <see cref="AnimationClip"/> assets.
        /// </summary>
        [Serializable]
        public sealed class ModelEntry
        {
            [Tooltip("The imported PMX model asset (a sub-asset generated by the .pmx importer).")]
            public PMXModel model;

            [Tooltip("Human friendly name shown in UI, derived from the model metadata.")]
            public string displayName = string.Empty;

            [Tooltip("Project-relative asset path of the source .pmx (used at runtime to locate texture files).")]
            public string sourcePath = string.Empty;

            [Tooltip("Ready-to-play AnimationClips for this model, converted from matching .vmd files.")]
            public List<AnimationClip> motions = new List<AnimationClip>();
        }

        [Tooltip("Every imported model together with its ready-to-play motion clips.")]
        public List<ModelEntry> entries = new List<ModelEntry>();

        /// <summary>Clears all entries. Used by the scanner before rebuilding the library.</summary>
        public void Clear()
        {
            entries.Clear();
        }

        /// <summary>Finds the entry for the given model, or null when the model is not indexed.</summary>
        public ModelEntry GetEntryForModel(PMXModel model)
        {
            if (model == null)
            {
                return null;
            }

            for (int i = 0; i < entries.Count; ++i)
            {
                if (entries[i].model == model)
                {
                    return entries[i];
                }
            }

            return null;
        }

        /// <summary>Returns the list of motion clips for a model, or null when the model is not indexed.</summary>
        public List<AnimationClip> GetMotionsForModel(PMXModel model)
        {
            ModelEntry entry = GetEntryForModel(model);
            return entry != null ? entry.motions : null;
        }

        /// <summary>Finds the entry for a project-relative source .pmx path, or null when not indexed.</summary>
        public ModelEntry GetEntryBySourcePath(string sourcePath)
        {
            if (string.IsNullOrEmpty(sourcePath))
            {
                return null;
            }

            string normalized = NormalizePath(sourcePath);
            for (int i = 0; i < entries.Count; ++i)
            {
                ModelEntry entry = entries[i];
                if (entry == null)
                {
                    continue;
                }
                if (string.Equals(NormalizePath(entry.sourcePath), normalized, System.StringComparison.OrdinalIgnoreCase))
                {
                    return entry;
                }
            }

            return null;
        }

        /// <summary>Returns a non-null, flattened list of all indexed model entries.</summary>
        public IReadOnlyList<ModelEntry> GetEntries()
        {
            return entries;
        }

        private static string NormalizePath(string path)
        {
            if (string.IsNullOrEmpty(path))
            {
                return string.Empty;
            }
            return path.Replace('\\', '/').TrimStart('/').ToLowerInvariant();
        }
    }
}
