using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEngine.Playables;
using UMT;

namespace MMDPlayer
{
    /// <summary>
    /// Total controller for the MMD player. Loads a <see cref="PMXModel"/> asset (built via UMT's
    /// <c>PMXImporter.BuildUnityObjects</c>), drives a VMD-derived <see cref="AnimationClip"/> on the
    /// model-root Animator through a PlayableGraph, and hands all solve/IK/physics responsibility to the
    /// <c>MMDTransformManager</c> produced by the import.
    ///
    /// Rules honoured here (see docs/Unity_MMD_半成品_方案_v0.1.md §5):
    ///  - We never write bone curves or drive bones directly; the MMDTransformManager is the only
    ///    authority on bone solving.
    ///  - We never turn SDEF skinning off at runtime (it deforms skirt/hair).
    ///  - All calls that could touch the native Bullet plugin are guarded / wrapped so an
    ///    unsupported platform degrades gracefully instead of crashing.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class MMDPlayerController : MonoBehaviour
    {
        [Header("Asset Library")]
        [Tooltip("Index of all imported models and their converted motion clips. Generated by the editor scanner.")]
        public MMDAssetLibrary library;

        [Header("Load")]
        [Tooltip("Model is built under this transform; null means this GameObject.")]
        public Transform modelAnchor;
        [Tooltip("Build a humanoid Avatar for the model (requires UMTResources). Turn off if the model's rig maps poorly.")]
        public bool createAvatar = true;
        [Tooltip("Automatically play the first available motion once the model is loaded.")]
        public bool autoPlayOnLoad = true;
        [Tooltip("Loop the current motion.")]
        public bool loop = false;

        [Header("Model Alignment (manual correction)")]
        [Tooltip("Euler rotation applied to the built model root (corrects differing MMD axis conventions).")]
        public Vector3 modelRotationOffset = Vector3.zero;
        [Tooltip("Position offset (relative to the anchor) applied to the built model root.")]
        public Vector3 modelPositionOffset = Vector3.zero;
        [Tooltip("Uniform scale applied to the built model root.")]
        public float modelScale = 1f;

        [Header("Playback")]
        [Tooltip("Playback speed multiplier applied to the active motion (clamped 0.25x - 3x).")]
        [Range(0.25f, 3f)] public float playbackSpeed = 1f;
        [Tooltip("Frame rate used for frame-stepping and the on-screen frame counter (VMD is typically 30fps).")]
        public int animationFps = 30;

        [Header("Model Presentation")]
        [Tooltip("Additional yaw (degrees) applied to the model root after load, for presenting the model.")]
        [Range(0f, 360f)] public float modelYaw;
        [Tooltip("Automatically run the shader fixer (replaces missing/error shaders) right after a model load.")]
        public bool fixShadersOnLoad = true;
        [Tooltip("Apply mobile-friendly runtime optimizations (frame rate cap, keep screen awake, lower mobile shadows).")]
        public bool optimizeForMobile = true;
        [Tooltip("Restore the last-edited model from PlayerPrefs when the app starts (no-op if none saved).")]
        public bool autoLoadLastModel = true;

        [Header("Physics")]
        [Tooltip("Master toggle for live Bullet physics; overridden to off when MMDPhysicsGuard reports it is unavailable.")]
        public bool livePhysics = true;

        /// <summary>Raised after a model has been built and aligned.</summary>
        public event Action OnModelLoaded;
        /// <summary>Raised whenever the active clip changes; the argument is the clip's name ("" when cleared).</summary>
        public event Action<string> OnClipChanged;
        /// <summary>Raised on a recoverable error or empty-state notification.</summary>
        public event Action<string> OnError;

        // --- runtime state ---
        private GameObject _root;
        private MMDTransformManager _tm;
        private MMDPhysicsManager _physics;
        private Animator _animator;
        private PMXModel _currentModel;
        private readonly List<AnimationClip> _currentMotions = new List<AnimationClip>();
        private AnimationClip _currentClip;
        private float _currentDuration;
        private bool _isPaused;
        private bool _physicsAvailable = true;

        // --- playable graph used to play the (non-legacy) clip on the Animator ---
        private PlayableGraph _graph;
        private AnimationPlayableOutput _output;
        private AnimationClipPlayable _clipPlayable;
        private bool _graphCreated;

        public MMDTransformManager TransformManager => _tm;
        public PMXModel CurrentModel => _currentModel;
        public IReadOnlyList<AnimationClip> CurrentMotions => _currentMotions;
        public AnimationClip CurrentClip => _currentClip;
        public float CurrentDuration => _currentDuration;
        public float CurrentTime => _clipPlayable.IsValid() ? (float)_clipPlayable.GetTime() : 0f;
        public bool PhysicsAvailable => _physicsAvailable;
        public bool IsPhysicsEnabled => _tm != null && _tm.livePhysics;
        public bool IsPaused => _isPaused;
        public bool IsPlaying => _currentClip != null && !_isPaused && _graphCreated;

        public bool HasModel => _currentModel != null;
        public bool HasClip => _currentClip != null;
        public string ModelName => _currentModel != null ? _currentModel.name : string.Empty;
        public string ClipName => _currentClip != null ? _currentClip.name : string.Empty;
        public float FrameRate => animationFps > 0 ? animationFps : 30f;
        public int CurrentFrame => Mathf.FloorToInt(CurrentTime * FrameRate);
        public float ModelYaw => modelYaw;

        /// <summary>Playback speed multiplier (clamped 0.25x - 3x). Setting it also updates the live playable.</summary>
        public float PlaybackSpeed
        {
            get => playbackSpeed;
            set => SetPlaybackSpeed(value);
        }

        private void Awake()
        {
            if (modelAnchor == null)
            {
                modelAnchor = transform;
            }

            _physicsAvailable = MMDPhysicsGuard.IsPhysicsAvailable();
            if (!_physicsAvailable)
            {
                livePhysics = false;
            }

            if (optimizeForMobile)
            {
                MMDMobilePerformance.Apply();
            }
        }

        private void Start()
        {
            TryAutoLoadLastModel();
        }

        private void OnDestroy()
        {
            DestroyGraph();
        }

        /// <summary>Loads the model that was active last time, if <see cref="autoLoadLastModel"/> is enabled.</summary>
        private void TryAutoLoadLastModel()
        {
            if (!autoLoadLastModel || library == null)
            {
                return;
            }

            string path = MMDPlayerPreferences.LoadModelPath();
            if (string.IsNullOrEmpty(path))
            {
                return;
            }

            bool loaded = LoadModelBySourcePath(path);
            if (!loaded)
            {
                Debug.Log("[MMD Player] No saved model available to restore: " + path);
            }
        }

        // ---------------------------------------------------------------------
        //  Loading
        // ---------------------------------------------------------------------

        /// <summary>
        /// Builds a PMX model into the model anchor and caches the UMT runtime components.
        /// Safe for <c>null</c> and any load failure (emits <see cref="OnError"/> and keeps an empty state).
        /// </summary>
        public void LoadModel(PMXModel modelAsset)
        {
            if (modelAsset == null)
            {
                UnloadModel();
                OnError?.Invoke("未指定模型（PMXModel 为空）。请先在资源库中选择一个模型。");
                return;
            }

            try
            {
                UnloadModel(); // destroy any previous model first

                PMXImportOptions options = new PMXImportOptions
                {
                    parent = modelAnchor != null ? modelAnchor : transform,
                    createAvatar = createAvatar,
                    applyRenames = true,
                    umtResources = LoadUMTResources(),
                };

                // The library entry carries the source .pmx path so PMXTextureLoader can resolve the
                // model's texture files from disk. This works while running inside the editor project.
                ApplySourcePathFromLibrary(modelAsset, options);

                PMXImportResult result = PMXImporter.BuildUnityObjects(modelAsset, options);

                _root = result.root;
                _tm = result.mmdTransformResult.transformManager;
                _physics = result.mmdTransformResult.physicsManager;
                _animator = _root.GetComponent<Animator>();
                _currentModel = modelAsset;

                if (_tm == null)
                {
                    throw new InvalidOperationException("UMT 未返回 MMDTransformManager（模型构建失败）。");
                }

                if (_animator == null)
                {
                    _animator = _root.AddComponent<Animator>();
                }
                _animator.applyRootMotion = false;
                _animator.cullingMode = AnimatorCullingMode.AlwaysAnimate;

                // Physics is only enabled where the native plugin actually exists.
                if (!_physicsAvailable)
                {
                    livePhysics = false;
                }
                _tm.livePhysics = _physicsAvailable && livePhysics;

                // Never disable SDEF at runtime; it keeps skirt/hair from collapsing.
                _tm.doSDEFSkinning = true;
                if (_tm.sdefComputeShader == null)
                {
                    _tm.sdefSkinningMode = SDEFSkinningMode.CPU;
                }

                _tm.transformEnabled = true;

                AlignModelToGround(_root.transform);

                if (fixShadersOnLoad)
                {
                    int fixedCount = MMDShaderFixer.FixMaterials(_root);
                    if (fixedCount > 0)
                    {
                        Debug.Log("[MMD Player] Fixed " + fixedCount + " material shader(s) on " + modelAsset.name);
                    }
                }

                _currentMotions.Clear();
                if (library != null)
                {
                    MMDAssetLibrary.ModelEntry entry = library.GetEntryForModel(modelAsset);
                    if (entry != null && entry.motions != null)
                    {
                        _currentMotions.AddRange(entry.motions);
                    }
                }

                if (autoPlayOnLoad && _currentMotions.Count > 0)
                {
                    PlayMotion(_currentMotions[0]);
                }

                SaveCurrentModelPath();
                OnModelLoaded?.Invoke();
            }
            catch (System.Runtime.InteropServices.DllNotFoundException e)
            {
                Debug.LogException(e);
                OnError?.Invoke($"{MMDPhysicsGuard.UnsupportedMessage}（模型构建需要 Bullet 原生库：{e.Message}）");
                UnloadModel();
            }
            catch (Exception e)
            {
                Debug.LogException(e);
                OnError?.Invoke($"模型加载失败：{e.Message}");
                UnloadModel();
            }
        }

        /// <summary>Destroys the current model and clears all animation state.</summary>
        public void UnloadModel()
        {
            DestroyGraph();

            if (_root != null)
            {
                if (Application.isPlaying)
                {
                    Destroy(_root);
                }
                else
                {
                    DestroyImmediate(_root);
                }
                _root = null;
            }

            _tm = null;
            _physics = null;
            _animator = null;
            _currentModel = null;
            _currentClip = null;
            _currentMotions.Clear();
            _currentDuration = 0f;
            _isPaused = false;
        }

        /// <summary>
        /// Uses the library entry's stored source path (if any) to configure texture loading for the
        /// runtime build. When running inside the editor the .pmx and its texture files exist on disk,
        /// so PMXTextureLoader can decode them; in a standalone build this may warn on missing textures.
        /// </summary>
        private void ApplySourcePathFromLibrary(PMXModel model, PMXImportOptions options)
        {
            string sourcePath = null;
            if (library != null)
            {
                MMDAssetLibrary.ModelEntry entry = library.GetEntryForModel(model);
                if (entry != null)
                {
                    sourcePath = entry.sourcePath;
                }
            }

            if (string.IsNullOrEmpty(sourcePath))
            {
                return;
            }

            // Convert a project-relative path ("Assets/...") into an absolute path, and the directory
            // that holds the texture files. Application.dataPath is the absolute path of the "Assets" folder.
            try
            {
                string absolute = Path.Combine(Application.dataPath, "..").Replace("\\", "/") + "/" +
                                  sourcePath.Replace("\\", "/").TrimStart('/');
                if (File.Exists(absolute))
                {
                    options.sourcePath = absolute;
                    options.textureBaseDirectory = Path.GetDirectoryName(absolute);
                }
            }
            catch (Exception e)
            {
                Debug.LogWarning("[MMD Player] Could not resolve model source path: " + e.Message);
            }
        }

        private static UMTResources LoadUMTResources()
        {
            UMTResources resources = Resources.Load<UMTResources>("UMTResources");
            if (resources == null)
            {
                throw new InvalidOperationException(
                    "未能加载 UMT 导入资源（Resources.Load<UMTResources>(\"UMTResources\")）。" +
                    "请确认 UMT 本地包的 Resources/UMTResources.asset 存在。");
            }
            return resources;
        }

        // ---------------------------------------------------------------------
        //  Playback
        // ---------------------------------------------------------------------

        /// <summary>Plays a converted VMD clip on the model-root Animator.</summary>
        public void PlayMotion(AnimationClip clip)
        {
            if (clip == null)
            {
                OnError?.Invoke("未选择动画（AnimationClip 为空）。");
                return;
            }

            if (_animator == null)
            {
                OnError?.Invoke("尚无已加载的模型，无法播放动画。");
                return;
            }

            _currentClip = clip;
            _currentDuration = clip.length;
            _isPaused = false;

            // Rebuild the graph per clip so we never need to Destroy() a playable directly.
            DestroyGraph();
            EnsureGraph();

            _clipPlayable = AnimationClipPlayable.Create(_graph, clip);
            _clipPlayable.SetLoop(loop);
            _clipPlayable.SetSpeed(playbackSpeed);
            _output.SetAnimationPlayable(_clipPlayable);
            _clipPlayable.Play();
            _graph.Play();

            OnClipChanged?.Invoke(clip.name);
        }

        public void Pause()
        {
            if (_clipPlayable.IsValid())
            {
                _clipPlayable.Pause();
                _isPaused = true;
            }
        }

        public void Resume()
        {
            if (_clipPlayable.IsValid())
            {
                _clipPlayable.Play();
                _isPaused = false;
            }
        }

        /// <summary>Stops playback and returns the model to its bind pose.</summary>
        public void StopAndReset()
        {
            DestroyGraph();
            ResetModelToBindPose();
            _currentClip = null;
            _currentDuration = 0f;
            _isPaused = false;
            OnClipChanged?.Invoke(string.Empty);
        }

        /// <summary>Seek to a given time (seconds) on the current clip.</summary>
        public void SetTime(float time)
        {
            if (!_clipPlayable.IsValid())
            {
                return;
            }

            float duration = _currentDuration;
            if (duration > 0f)
            {
                time = Mathf.Clamp(time, 0f, duration);
            }
            else if (time < 0f)
            {
                time = 0f;
            }

            _clipPlayable.SetTime(time);
        }

        public void SetLoop(bool on)
        {
            loop = on;
            if (_clipPlayable.IsValid())
            {
                _clipPlayable.SetLoop(on);
            }
        }

        /// <summary>Sets the playback speed multiplier for the active motion (clamped 0.25x - 3x).</summary>
        public void SetPlaybackSpeed(float speed)
        {
            playbackSpeed = Mathf.Clamp(speed, 0.25f, 3f);
            if (_clipPlayable.IsValid())
            {
                _clipPlayable.SetSpeed(playbackSpeed);
            }
        }

        /// <summary>Steps the current motion forward (+) or backward (-) by the given number of frames.</summary>
        public void StepFrame(int frames)
        {
            if (!_clipPlayable.IsValid() || _currentDuration <= 0f)
            {
                return;
            }
            SetTime(CurrentTime + frames * (1f / FrameRate));
        }

        /// <summary>Convenience toggle: resumes if paused, otherwise pauses the current motion.</summary>
        public void PlayPauseToggle()
        {
            if (!HasClip)
            {
                return;
            }
            if (_isPaused)
            {
                Resume();
            }
            else
            {
                Pause();
            }
        }

        /// <summary>Rewinds the current motion to the start and resumes it (does not change the loop setting).</summary>
        public void RestartClip()
        {
            if (!HasClip)
            {
                return;
            }
            SetTime(0f);
            _isPaused = false;
            if (_clipPlayable.IsValid())
            {
                _clipPlayable.Play();
            }
        }

        /// <summary>Returns the world-space bounds of the loaded model, or a unit bounds around the anchor.</summary>
        public Bounds GetModelBounds()
        {
            return _root != null ? ComputeWorldBounds(_root.transform) : new Bounds(transform.position, Vector3.one);
        }

        /// <summary>Sets the additional yaw (degrees) applied to the model root for presentation.</summary>
        public void SetModelYaw(float yaw)
        {
            modelYaw = Mathf.Repeat(yaw, 360f);
            ApplyModelRotation();
        }

        /// <summary>Rotates the model root by the given delta (degrees) around its local Y axis.</summary>
        public void RotateModel(float deltaYaw)
        {
            SetModelYaw(modelYaw + deltaYaw);
        }

        /// <summary>Runs the shader fixer over the loaded model immediately (also runs automatically on load).</summary>
        public void FixModelShaders()
        {
            if (_root != null)
            {
                MMDShaderFixer.FixMaterials(_root);
            }
        }

        /// <summary>
        /// Loads a model by its project-relative source .pmx path (see <see cref="MMDAssetLibrary.sourcePath"/>).
        /// Returns true when the library contains that model and it was loaded.
        /// </summary>
        public bool LoadModelBySourcePath(string sourcePath)
        {
            if (library == null)
            {
                return false;
            }
            MMDAssetLibrary.ModelEntry entry = library.GetEntryBySourcePath(sourcePath);
            if (entry == null || entry.model == null)
            {
                return false;
            }
            LoadModel(entry.model);
            return true;
        }

        /// <summary>Stores the current model's source path so the next launch can restore it.</summary>
        private void SaveCurrentModelPath()
        {
            if (library == null || _currentModel == null)
            {
                return;
            }

            MMDAssetLibrary.ModelEntry entry = library.GetEntryForModel(_currentModel);
            if (entry != null && !string.IsNullOrEmpty(entry.sourcePath))
            {
                MMDPlayerPreferences.SaveModelPath(entry.sourcePath);
            }
        }

        /// <summary>Returns the names of all vertex morphs (blend shapes) present on the loaded model.</summary>
        public List<string> GetMorphNames()
        {
            List<string> names = new List<string>();
            if (_root == null)
            {
                return names;
            }

            HashSet<string> seen = new HashSet<string>();
            SkinnedMeshRenderer[] renderers = _root.GetComponentsInChildren<SkinnedMeshRenderer>(true);
            if (renderers == null)
            {
                return names;
            }

            foreach (SkinnedMeshRenderer renderer in renderers)
            {
                if (renderer == null || renderer.sharedMesh == null)
                {
                    continue;
                }

                int count = renderer.sharedMesh.blendShapeCount;
                for (int i = 0; i < count; ++i)
                {
                    string name = renderer.sharedMesh.GetBlendShapeName(i);
                    if (!string.IsNullOrEmpty(name) && seen.Add(name))
                    {
                        names.Add(name);
                    }
                }
            }

            return names;
        }

        /// <summary>Sets the weight (0..1) of a morph on every matching blend shape.</summary>
        public void SetMorph(string name, float weight)
        {
            if (_root == null)
            {
                return;
            }

            weight = Mathf.Clamp01(weight);
            SkinnedMeshRenderer[] renderers = _root.GetComponentsInChildren<SkinnedMeshRenderer>(true);
            if (renderers == null)
            {
                return;
            }

            foreach (SkinnedMeshRenderer renderer in renderers)
            {
                if (renderer == null || renderer.sharedMesh == null)
                {
                    continue;
                }

                int index = renderer.sharedMesh.GetBlendShapeIndex(name);
                if (index >= 0)
                {
                    renderer.SetBlendShapeWeight(index, weight * 100f); // blend-shape weights are 0..100
                }
            }
        }

        /// <summary>Enables or disables live physics, respecting platform availability.</summary>
        public void TogglePhysics(bool on)
        {
            if (!_physicsAvailable)
            {
                livePhysics = false;
                if (_tm != null)
                {
                    _tm.livePhysics = false;
                }
                OnError?.Invoke(MMDPhysicsGuard.UnsupportedMessage);
                return;
            }

            livePhysics = on;
            if (_tm != null)
            {
                _tm.livePhysics = on;
                try
                {
                    _tm.ResetPhysics();
                }
                catch (Exception e)
                {
                    Debug.LogException(e);
                    _tm.livePhysics = false;
                }
            }
        }

        /// <summary>Re-applies the model's bind pose without touching the native physics library.</summary>
        public void ResetModel()
        {
            StopAndReset();
        }

        // ---------------------------------------------------------------------
        //  Internals
        // ---------------------------------------------------------------------

        private void EnsureGraph()
        {
            if (_graphCreated && _graph.IsValid())
            {
                return;
            }

            _graph = PlayableGraph.Create("MMDPlayer_Animation");
            _output = AnimationPlayableOutput.Create(_graph, "MMDPlayer_Animation", _animator);
            _graphCreated = true;
        }

        private void DestroyGraph()
        {
            if (_graphCreated && _graph.IsValid())
            {
                _graph.Destroy();
            }
            _graphCreated = false;
            _clipPlayable = default;
        }

        /// <summary>
        /// Resets every bone transform to its captured initial pose and re-seeds the solver caches.
        /// This avoids calling <c>MMDTransformManager.ResetToBindPose</c>, which also re-initialises the
        /// native physics context and would throw on platforms without the Bullet plugin.
        /// </summary>
        private void ResetModelToBindPose()
        {
            if (_tm == null)
            {
                return;
            }

            try
            {
                MMDBoneTransform[] bones = _tm.bones;
                if (bones != null)
                {
                    foreach (MMDBoneTransform bone in bones)
                    {
                        if (bone == null)
                        {
                            continue;
                        }

                        bone.transform.localPosition = bone.initialLocalPosition;
                        bone.transform.localRotation = bone.initialLocalRotation;
                        bone.solverResetPending = true;
                    }
                }

                _tm.RebuildNativeCaches();
            }
            catch (Exception e)
            {
                Debug.LogException(e);
            }
        }

        /// <summary>
        /// Applies the model root's alignment (ground the feet to y≈0, apply scale/rotation/position
        /// offsets). Orientation conventions vary per MMD model, so manual correction fields are exposed;
        /// this default guesses the safe case (feet on the ground, model at its native size).
        /// </summary>
        private void AlignModelToGround(Transform root)
        {
            if (root == null)
            {
                return;
            }

            root.localRotation = Quaternion.Euler(modelRotationOffset) * Quaternion.Euler(0f, modelYaw, 0f);
            root.localScale = Vector3.one * modelScale;
            root.localPosition = modelPositionOffset;

            Bounds bounds = ComputeWorldBounds(root);
            if (!float.IsNaN(bounds.min.y) && !float.IsInfinity(bounds.min.y))
            {
                Vector3 position = root.position;
                position.y -= bounds.min.y; // lift the lowest point to y = 0
                root.position = position;
            }
        }

        /// <summary>Applies the model yaw to the built root, preserving the manual rotation offset.</summary>
        private void ApplyModelRotation()
        {
            if (_root == null)
            {
                return;
            }
            _root.transform.localRotation = Quaternion.Euler(modelRotationOffset) * Quaternion.Euler(0f, modelYaw, 0f);
        }

        private static Bounds ComputeWorldBounds(Transform root)
        {
            Renderer[] renderers = root.GetComponentsInChildren<Renderer>(true);
            if (renderers == null || renderers.Length == 0)
            {
                return new Bounds(Vector3.zero, Vector3.one);
            }

            Bounds bounds = renderers[0].bounds;
            for (int i = 1; i < renderers.Length; ++i)
            {
                bounds.Encapsulate(renderers[i].bounds);
            }

            return bounds;
        }
    }
}
